# -*- coding: utf-8 -*-
"""chat_with_pdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nP0BlXW4zoSXQxcdOXkJfG9ZmVAw3IyH
"""

!pip install langchain
!pip install openai
!pip install PyPDF2
!pip install faiss-cpu
!pip install tiktoken

from PyPDF2 import PdfReader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import ElasticVectorSearch, Pinecone, Weaviate, FAISS

# Get your API keys from openai, you will need to create an account.
# Here is the link to get the keys: https://platform.openai.com/account/billing/overview
import os
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_KEY"

reader = PdfReader('/content/Data-Science-Notes.pdf')

reader

# read data from the file and put them into a variable called raw_text
raw_text = ''
for i, page in enumerate(reader.pages):
    text = page.extract_text()
    if text:
        raw_text += text

raw_text[:100]

# We need to split the text that we read into smaller chunks so that during information retreival we don't hit the token size limits.

text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 1000,
    chunk_overlap  = 200,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)

len(texts)

texts[0]

# Download embeddings from OpenAI
embeddings = OpenAIEmbeddings()

docsearch = FAISS.from_texts(texts, embeddings)

docsearch

from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI

chain = load_qa_chain(OpenAI(), chain_type="stuff")

query = "Who is author of these notes?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "What are steps in data science?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "What are assumptions of linear regression?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "What is differen between precision and recall?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "How the KKN classifier works?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

